Repository xmos/fwk_voice, pull requests merged in 2022-07, with the labels that each got.

#331 IC VNR doc update
  examples/bare-metal/agc/src/agc_app.c
  examples/bare-metal/ic/src/ic_test_task.c
  examples/bare-metal/pipeline_multi_threaded/README.rst
  examples/bare-metal/pipeline_multi_threaded/src/pipeline.c
  examples/bare-metal/pipeline_single_threaded/README.rst
  examples/bare-metal/pipeline_single_threaded/src/pipeline.c
  examples/bare-metal/shared_src/calc_vnr_pred/src/calc_vnr_pred.c
  modules/lib_agc/api/agc_api.h
  modules/lib_agc/api/agc_profiles.h
  modules/lib_agc/doc/src/overview.rst
  modules/lib_agc/src/agc_impl.c
  modules/lib_ic/api/ic_defines.h
  modules/lib_ic/api/ic_state.h
  modules/lib_ic/doc/src/overview.rst
  modules/lib_ic/src/ic.c
  modules/lib_ic/src/ic_low_level.c
  test/lib_agc/test_process_frame/src/test_input_output.c
  test/lib_agc/test_process_frame/src/test_lc_transitions.c
  test/lib_agc/test_process_frame/src/test_loss_control.c
  test/lib_agc/test_process_frame/src/test_lower_threshold.c
  test/lib_agc/test_process_frame/src/test_max_gain.c
  test/lib_agc/test_process_frame/src/test_min_gain.c
  test/lib_agc/test_process_frame/src/test_no_gain.c
  test/lib_agc/test_process_frame/src/test_process_frame.h
  test/lib_agc/test_process_frame/src/test_reset.c
  test/lib_agc/test_process_frame/src/test_simple_gain.c
  test/lib_agc/test_process_frame/src/test_soft_clipping.c
  test/lib_agc/test_process_frame/src/test_upper_threshold.c
  test/lib_agc/test_process_frame/src/test_vad_flag.c
  test/lib_agc/test_process_frame/src/test_vnr_flag.c
  test/lib_ic/ic_unit_tests/src/test_ic_h_hat_leakage.c
  test/lib_ic/py_c_frame_compare/ic_test.c
Labels: type:documentation

#333 Feature/adec startup
  Jenkinsfile
  modules/lib_adec/src/adec_impl.c
  test/CMakeLists.txt
  test/lib_adec/CMakeLists.txt
  test/lib_adec/test_adec_startup/CMakeLists.txt
  test/lib_adec/test_adec_startup/test_adec_startup.py
  test/lib_adec/test_wav_adec/src/pipeline.c
  test/pipeline/conftest.py
Labels: type:bug, size:SM

#323 Feature/rename documentation
  .github/workflows/docs.yml
  CHANGELOG.rst
  README.rst
  doc/README.rst
  doc/getting_started.rst
  doc/user_guide/audio_processing/index.rst
  doc/user_guide/index.rst
  examples/bare-metal/aec_1_thread/README.rst
  examples/bare-metal/aec_2_threads/README.rst
  examples/bare-metal/agc/README.rst
  examples/bare-metal/doc/index.rst
  examples/bare-metal/ic/README.rst
  examples/bare-metal/pipeline_alt_arch/README.rst
  examples/bare-metal/pipeline_multi_threaded/README.rst
  examples/bare-metal/pipeline_single_threaded/README.rst
  examples/bare-metal/vad/README.rst
  examples/bare-metal/vnr/README.rst
  index.rst
  modules/lib_adec/doc/index.rst
  modules/lib_adec/doc/src/getting_started.rst
  modules/lib_aec/doc/index.rst
  modules/lib_aec/doc/src/getting_started.rst
  modules/lib_agc/doc/index.rst
  modules/lib_agc/doc/src/getting_started.rst
  modules/lib_ic/doc/index.rst
  modules/lib_ic/doc/src/getting_started.rst
  modules/lib_ns/doc/index.rst
  modules/lib_ns/doc/src/getting_started.rst
  modules/lib_vad/doc/index.rst
  modules/lib_vad/doc/src/getting_started.rst
  modules/lib_vnr/doc/index.rst
  modules/lib_vnr/doc/src/getting_started.rst
  modules/lib_vnr/python/utils/xformer/README.rst
  modules/lib_vnr/src/features/mel_filter_512_24_compact.h
  modules/lib_vnr/src/inference/model/vnr_quant_spec_defines.h
  modules/lib_vnr/src/inference/model/vnr_tensor_arena_size.h
  settings.json
  test/stage_b/test_stage_b_frame.py
Labels: type:documentation, size:SM

#335 Ported py_vnr v0.2.1
  examples/bare-metal/pipeline_multi_threaded/src/pipeline.c
  examples/bare-metal/pipeline_single_threaded/src/pipeline.c
  modules/lib_vnr/api/features/vnr_features_state.h
  modules/lib_vnr/python/model/model_output/model_history.npy
  modules/lib_vnr/python/model/model_output/model_qaware.h5
  modules/lib_vnr/python/model/model_output/model_qaware.tflite
  modules/lib_vnr/python/model/model_output/qaware_model_history.npy
  modules/lib_vnr/python/model/model_output/trained_model.h5
  modules/lib_vnr/python/model/model_output/trained_model.tflite
  modules/lib_vnr/python/utils/xformer/README.rst
  modules/lib_vnr/src/features/vnr_features.c
  modules/lib_vnr/src/features/vnr_features_priv.c
  modules/lib_vnr/src/features/vnr_features_priv.h
  modules/lib_vnr/src/inference/model/model_qaware_xcore.tflite
  modules/lib_vnr/src/inference/model/trained_model_xcore.tflite
  modules/lib_vnr/src/inference/model/vnr_model_data.c
  modules/lib_vnr/src/inference/model/vnr_quant_spec_defines.h
  test/lib_ic/test_calc_vnr_pred/test_calc_vnr_pred.py
  test/lib_vnr/py_c_feature_compare/test_vnr_feature_extraction.py
  test/lib_vnr/test_wav_vnr/readme
  test/lib_vnr/test_wav_vnr/test_wav_vnr.py
  test/lib_vnr/vnr_unit_tests/feature_extraction/src/test_vnr_extract_features.c
  test/lib_vnr/vnr_unit_tests/feature_extraction/src/test_vnr_priv_make_slice.c
  test/lib_vnr/vnr_unit_tests/feature_extraction/test_utils.py
  test/lib_vnr/vnr_unit_tests/feature_extraction/test_vnr_extract_features.py
  test/lib_vnr/vnr_unit_tests/feature_extraction/test_vnr_priv_make_slice.py
  test/lib_vnr/vnr_unit_tests/full/src/test_vnr_full.c
  test/lib_vnr/vnr_unit_tests/full/test_vnr_full.py
  test/lib_vnr/vnr_unit_tests/inference/test_vnr_inference.py
  test/stage_b/test_stage_b_frame.py
Labels: type:enhancement, size:SM
