Repository xmos/fwk_voice, pull requests merged in 2022-06, with the labels that each got.

#314 Feature/avona issue 296
  doc/Doxyfile.inc
  examples/bare-metal/vnr/CMakeLists.txt
  modules/lib_vnr/CMakeLists.txt
  modules/lib_vnr/api/common/vnr_defines.h
  modules/lib_vnr/api/features/vnr_features_state.h
  modules/lib_vnr/api/inference/vnr_inference_api.h
  modules/lib_vnr/api/inference/xtflm_conf.h
  modules/lib_vnr/doc/index.rst
  modules/lib_vnr/doc/src/getting_started.rst
  modules/lib_vnr/doc/src/reference/api.rst
  modules/lib_vnr/doc/src/reference/common_defines.rst
  modules/lib_vnr/doc/src/reference/header_files.rst
  modules/lib_vnr/doc/src/reference/index.rst
  modules/lib_vnr/doc/src/reference/state.rst
  modules/lib_vnr/doc/src/xformer.rst
  modules/lib_vnr/python/utils/xformer/README.rst
  modules/lib_vnr/src/inference/vnr_inference.cc
  modules/lib_vnr/src/inference/vnr_inference_priv.cc
  modules/lib_vnr/src/inference/vnr_inference_priv.h
  test/lib_vnr/CMakeLists.txt
  test/lib_vnr/py_c_feature_compare/build_vnr_feature_extraction.py
  test/lib_vnr/py_c_feature_compare/extract_state.py
  test/lib_vnr/vnr_unit_tests/feature_extraction/src/test_vnr_extract_features.c
  test/lib_vnr/vnr_unit_tests/inference/CMakeLists.txt
  test/lib_vnr/vnr_unit_tests/inference/src/test_vnr_inference.c
  test/lib_vnr/vnr_unit_tests/inference/src/test_vnr_priv_feature_quantise.c
  test/lib_vnr/vnr_unit_tests/inference/src/test_vnr_priv_output_dequantise.c
Labels: type:documentation, size:SM

#315 Add Amazon WWE to pipeline tests
  Jenkinsfile
  test/pipeline/conftest.py
  test/pipeline/pipeline_test_utils.py
  test/pipeline/run_amazon_wwe.py
  test/pipeline/run_sensory.py
  test/pipeline/test_pipeline.py
Labels: type:enhancement, size:SM

#321 Feature/new ic control
  Jenkinsfile
  examples/bare-metal/ic/src/ic_test_task.c
  examples/bare-metal/pipeline_alt_arch/CMakeLists.txt
  examples/bare-metal/pipeline_multi_threaded/CMakeLists.txt
  examples/bare-metal/pipeline_multi_threaded/src/pipeline.c
  examples/bare-metal/pipeline_multi_threaded/src/pipeline_state.h
  examples/bare-metal/pipeline_single_threaded/CMakeLists.txt
  examples/bare-metal/pipeline_single_threaded/src/pipeline.c
  examples/bare-metal/pipeline_single_threaded/src/pipeline_state.h
  examples/bare-metal/shared_src/calc_vnr_pred/src/calc_vnr_pred.c
  modules/lib_ic/api/ic_api.h
  modules/lib_ic/api/ic_defines.h
  modules/lib_ic/api/ic_state.h
  modules/lib_ic/src/ic.c
  modules/lib_ic/src/ic_low_level.c
  modules/lib_ic/src/ic_low_level.h
  test/lib_ic/py_c_frame_compare/build_ic_frame_proc.py
  test/lib_ic/py_c_frame_compare/ic_test.c
  test/lib_ic/py_c_frame_compare/test_ic_frame.py
  test/lib_ic/test_calc_vnr_pred/CMakeLists.txt
  test/lib_ic/test_ic_spec/test_ic_spec.py
  test/lib_vnr/CMakeLists.txt
  test/lib_vnr/vnr_unit_tests/feature_extraction/CMakeLists.txt
  test/lib_vnr/vnr_unit_tests/full/CMakeLists.txt
  test/lib_vnr/vnr_unit_tests/inference/CMakeLists.txt
  test/stage_b/build_c_code.py
  test/stage_b/extract_state.py
  test/stage_b/ic_vad_test.c
  test/stage_b/ic_vnr_test.c
  test/stage_b/test_stage_b_frame.py
Labels: type:enhancement, size:M
