Repository xmos/fwk_voice, pull requests merged in 2022-05, with the labels that each got.

#289 Recalculate FFT output headroom in case the headroom reported by bfp_…
  modules/lib_aec/src/aec_impl.c
  modules/lib_ns/src/ns_impl.c
  modules/lib_vnr/src/features/vnr_features_priv.c
  requirements.txt
Labels: type:bug, size:SM

#290 Feature/bfp init calc hr
  modules/lib_aec/src/aec_impl.c
  modules/lib_aec/src/aec_l2_impl.c
  modules/lib_aec/src/aec_priv_impl.c
Labels: type:enhancement, size:SM

#295 Feature/restructure targets
  examples/bare-metal/aec_1_thread/CMakeLists.txt
  examples/bare-metal/agc/CMakeLists.txt
  examples/bare-metal/pipeline_alt_arch/CMakeLists.txt
  examples/bare-metal/pipeline_multi_threaded/CMakeLists.txt
  examples/bare-metal/pipeline_single_threaded/CMakeLists.txt
  examples/bare-metal/shared_src/CMakeLists.txt
  examples/bare-metal/shared_src/external_deps/lib_xs3_math/CMakeLists.txt
  modules/lib_adec/CMakeLists.txt
  modules/lib_aec/CMakeLists.txt
  modules/lib_agc/CMakeLists.txt
  modules/lib_ic/CMakeLists.txt
  modules/lib_ns/CMakeLists.txt
  modules/lib_vad/CMakeLists.txt
  modules/lib_vnr/CMakeLists.txt
  test/lib_vad/compare_xc_c/CMakeLists.txt
  test/lib_vnr/vnr_unit_tests/feature_extraction/CMakeLists.txt
  test/lib_vnr/vnr_unit_tests/full/CMakeLists.txt
  test/lib_vnr/vnr_unit_tests/inference/CMakeLists.txt
  test/test_hpf/CMakeLists.txt
Labels: type:bug, size:SM

#278 memory investigations
  Jenkinsfile
  modules/lib_vnr/CMakeLists.txt
  modules/lib_vnr/api/inference/vnr_inference_state.h
  modules/lib_vnr/api/inference/vnr_tensor_arena_size.h
  modules/lib_vnr/src/inference/vnr_inference.cc
  requirements.txt
  test/lib_vnr/profile_memory/CMakeLists.txt
  test/lib_vnr/profile_memory/src/profile_vad.c
  test/lib_vnr/test_wav_vnr/convert_model.py
Labels: type:investigation

#283 Integrate latest model
  examples/bare-metal/shared_src/external_deps/fetch_deps.cmake
  modules/lib_vnr/api/inference/vnr_quant_spec_defines.h
  modules/lib_vnr/api/inference/vnr_tensor_arena_size.h
  modules/lib_vnr/src/inference/model/vnr_model_data.c
  test/lib_vnr/py_c_feature_compare/test_vnr_feature_extraction.py
  test/lib_vnr/test_wav_vnr/convert_model.py
  test/lib_vnr/test_wav_vnr/model/model_output/model_history.npy
  test/lib_vnr/test_wav_vnr/model/model_output/model_qaware.h5
  test/lib_vnr/test_wav_vnr/model/model_output/model_qaware.tflite
  test/lib_vnr/test_wav_vnr/model/model_output/model_qaware_xcore.tflite
  test/lib_vnr/test_wav_vnr/model/model_output/qaware_model_history.npy
  test/lib_vnr/test_wav_vnr/model/model_output/trained_model.h5
  test/lib_vnr/test_wav_vnr/model/model_output_0_0_2/model_history.npy
  test/lib_vnr/test_wav_vnr/model/model_output_0_0_2/model_qaware.h5
  test/lib_vnr/test_wav_vnr/model/model_output_0_0_2/model_qaware.tflite
  test/lib_vnr/test_wav_vnr/model/model_output_0_0_2/model_qaware_xcore.tflite
  test/lib_vnr/test_wav_vnr/model/model_output_0_0_2/trained_model.h5
  test/lib_vnr/test_wav_vnr/model/model_output_0_0_2/vnr_model_data.c
  test/lib_vnr/test_wav_vnr/model/model_output_0_0_2/vnr_model_data.h
  test/lib_vnr/test_wav_vnr/run_xtflminterpreter.py
  test/lib_vnr/test_wav_vnr/test_wav_vnr.py
  test/lib_vnr/vnr_unit_tests/conftest.py
  test/lib_vnr/vnr_unit_tests/feature_extraction/test_utils.py
  test/lib_vnr/vnr_unit_tests/full/test_vnr_full.py
  test/lib_vnr/vnr_unit_tests/inference/test_vnr_inference.py
  test/lib_vnr/vnr_unit_tests/inference/test_vnr_priv_feature_quantise.py
  test/lib_vnr/vnr_unit_tests/inference/test_vnr_priv_output_dequantise.py
Labels: type:enhancement, size:SM

#286 Feature/multi tile example
  examples/bare-metal/pipeline_multi_threaded/src/main.xc
  examples/bare-metal/pipeline_multi_threaded/src/pipeline.c
  examples/bare-metal/pipeline_multi_threaded/src/test_wav.c
  examples/bare-metal/pipeline_single_threaded/src/main.xc
  examples/bare-metal/pipeline_single_threaded/src/pipeline.c
  examples/bare-metal/pipeline_single_threaded/src/pipeline_state.h
  examples/bare-metal/pipeline_single_threaded/src/test_wav.c
Labels: type:enhancement, size:SM
